name: stellareader
description: "A simple Android PDF and EPUB reader."
publish_to: 'none'
version: 0.3.0+5

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_riverpod: any
  go_router: any
  pdfx: any
  sqflite: any
  path_provider: any
  file_picker: any
  epub_view: any
  universal_io: any
  receive_sharing_intent: any
  dio: any
  path: any
  xml: ^6.5.0
  package_info_plus: ^8.3.1
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
